version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.3
    container_name: netra_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=netra
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: netra_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
